<?php require "partials/head.php"; ?>
<?php require "partials/nav.php"; ?>



<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="dashboard.css" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="/Dashboard/css/reports.css">

<style>
  .search-filter {
    display: none;
  }

  .report-container {
    display: none;
  }
</style>

<body>
  <div class="content">
    <h2>Reports
      <?php echo " (" . $_SESSION['user']['email'] . " the " . $_SESSION['user']['position'] . ") " ?>
    </h2>
    <div class="container">
      <div class="row justify-content-center mt-3">
        <div class="col text-center">
          <button class="btn btn-primary" onclick="showReport('sales')">Show Sales Report</button>
          <button class="btn btn-primary" onclick="showReport('inventory')">Show Inventory Report</button>
          <button class="btn btn-primary" onclick="showReport('feedback')">Show Feedback Report</button>
          <!-- <button class="btn btn-primary" onclick="showReport('userlogs')">Show Userlogs Report</button> -->
        </div>
      </div>

      <div id="salesReportContainer" class="report-container">
        <div class="search-filter">
          <div class="row mt-2 align-items-center">
            <div class="col-4">
              <label for="startDateSales">Start Date:</label>
              <input type="date" id="startDateSales" class="form-control">
            </div>
            <div class="col-4">
              <label for="endDateSales">End Date:</label>
              <input type="date" id="endDateSales" class="form-control">
            </div>
            <div class="col-4">
              <button onclick="searchSales()" class="btn btn-primary mt-4">Search</button>
            </div>
          </div>
        </div>
        <div class="table-responsive" style="max-height: 800px; overflow-y: auto;" id="content">
          <p><strong>Date Generated: </strong><?= date('F j, Y') ?> </p>
          <p><strong>Report Generated by: </strong><?= ucwords(str_replace('_', ' ', $Admin['username'])) ?> </p>
          <table id="salesTable" class="report-table table">
            <thead>
              <tr>
                <th>Payment ID</th>
                <th>Order Date Time</th>
                <th>Amount Paid</th>
                <th>Payment Type</th>
                <th>Reference No.</th>
                <th>Customer ID</th>

              </tr>
            </thead>
            <tbody id="tableBodySales" style="height: 100%;"></tbody>
          </table>
        </div>
        <div class="row justify-content-center mb-2">
          <div class="col text-center">
            <!-- <button class="download-btn btn btn-primary" data-report-type="sales" onclick="downloadPDF('salesReportContainer')">Print as PDF</button> -->
          </div>
          <div class="col text-center">

          </div><button class="download-btn btn btn-primary btn-block" data-report-type="sales" onclick="demoFromHTML()">Download as PDF</button>
        </div>
      </div>

      <div id="inventoryReportContainer" class="report-container">
        <div class="search-filter">
          <div class="row align-items-center">
            <div class="col-5">
              <label for="quantityFilterInventory">Filter by Item Name:</label>
              <input type="text" id="quantityFilterInventory" class="form-control" onchange="filterTable('inventory')">
              <!-- <select id="quantityFilterInventory" class="form-control" onchange="filterTable('inventory')">
                <option value="">All</option>
                <option value="deduct">Deduct</option>
                <option value="add">Add</option>
              </select> -->
            </div>
            <div class="col-7">
              <!-- <button onclick="filterTable('inventory')" class="btn btn-primary mt-4">Search</button> -->
            </div>
          </div>
        </div>
        <div class="table-responsive" style="max-height: 800px; overflow-y: auto;" id="content2">
          <p><strong>Date Generated: </strong><?= date('F j, Y') ?> </p>
          <p><strong>Report Generated by: </strong><?= ucwords(str_replace('_', ' ', $Admin['username'])) ?> </p>
          <table id="inventoryTable" class="report-table table mt-2">
            <thead>
              <tr>
                <th>Inventory Report id</th>
                <th>Item</th>
                <th>Quantity Change</th>
                <th>Unit</th>
                <th>Report Type</th>
                <th>Note</th>
                <th>Date Time</th>
              </tr>
            </thead>
            <tbody id="inventoryTableBody" style="height: 100%;"></tbody>
          </table>
        </div>

        <div class="row justify-content-center mb-2">
          <div class="col text-center">
            <!-- <button class="download-btn btn btn-primary" data-report-type="inventory" onclick="downloadPDF('inventoryReportContainer')">Print as PDF</button> -->
          </div>
          <div class="col text-center">

          </div><button class="download-btn btn btn-primary btn-block" data-report-type="inventory" onclick="demoFromHTML2()">Download as PDF</button>
        </div>
      </div>


      <div>
        <div id="feedbackReportContainer" class="report-container">
          <div class="search-filter">
            <div class="row mt-2 align-items-center">
              <div class="col-4">
                <label for="startDateFeedback">Start Date:</label>
                <input type="date" id="startDateFeedback" class="form-control">
              </div>
              <div class="col-4">
                <label for="endDateFeedback">End Date:</label>
                <input type="date" id="endDateFeedback" class="form-control">
              </div>
              <div class="col-4">
                <button onclick="filterTable('feedback')" class="btn btn-primary mt-4">Search</button>
              </div>
            </div>
          </div>
          <div id="content3">
            <p><strong>Date Generated: </strong><?= date('F j, Y') ?> </p>
            <p><strong>Report Generated by: </strong><?= ucwords(str_replace('_', ' ', $Admin['username'])) ?> </p>
            <table id="feedbackTable" class="report-table table">
              <thead>
                <tr>
                  <th>Feedback ID</th>
                  <th>Title</th>
                  <th>Description</th>
                  <th>Date and time</th>
                  <th>Customer ID</th>
                </tr>
              </thead>
              <tbody id="tableBodyFeedback"></tbody>
            </table>
          </div>
          <div class="row justify-content-center mb-2">
            <div class="col text-center">
              <!-- <button class="download-btn btn btn-primary" data-report-type="feedback" onclick="downloadPDF('feedbackReportContainer')">Print as PDF</button> -->
            </div>
            <div class="col text-center">

            </div><button class="download-btn btn btn-primary btn-block" data-report-type="sales" onclick="demoFromHTML3()">Download as PDF</button>
          </div>
        </div>
      </div>

      <div id="userlogsReportContainer" class="report-container">
        <div class="search-filter">
          <div class="row mt-2 align-items-center">
            <div class="col-4">
              <label for="startDateUserlog">Start Date:</label>
              <input type="date" id="startDateUserlog" class="form-control">
            </div>
            <div class="col-4">
              <label for="endDateUserlog">End Date:</label>
              <input type="date" id="endDateUserlog" class="form-control">
            </div>
            <div class="col-4">
              <button onclick="filterTable('userlogs')" class="btn btn-primary mt-4">Search</button>
            </div>
          </div>
        </div>
        <div class="table-responsive" style="max-height: 800px; overflow-y: auto;" id="content4">
          <p><strong>Date Generated: </strong><?= date('F j, Y') ?> </p>
          <p><strong>Report Generated by: </strong><?= ucwords(str_replace('_', ' ', $Admin['username'])) ?> </p>
          <table id="userlogsTable" class="report-table table mt-2">
            <thead>
              <tr>
                <th>Log ID</th>
                <th>Date and Time</th>
                <th>Log Information</th>
                <th>Employee ID</th>
              </tr>
            </thead>
            <tbody id="userlogsTableBody" style="height: 100%;"></tbody>
          </table>
        </div>
        <div class="row justify-content-center mb-2">
          <div class="col text-center">
            <!-- <button class="download-btn btn btn-primary" data-report-type="feedback" onclick="downloadPDF('userlogsReportContainer')">Print as PDF</button> -->
          </div>
          <div class="col text-center">

          </div><button class="download-btn btn btn-primary btn-block" data-report-type="sales" onclick="demoFromHTML4()">Download as PDF</button>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="/Dashboard/js-dashboard/reports.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.3.1/jspdf.umd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.16/jspdf.plugin.autotable.min.js"></script>


    <script>
      //PRINTING SALES REPORT
      function demoFromHTML() {
        // Ensure jsPDF and autoTable are correctly initialized
        var {
          jsPDF
        } = window.jspdf;
        var doc = new jsPDF('p', 'pt', 'letter');

        // Source is the table
        var source = document.getElementById('content');

        // Variables for content extraction
        var paragraph = [];
        var rows = [];
        var header = [];
        var top = '';

        // Extract paragraphs
        source.querySelectorAll('p').forEach(p => {
          paragraph.push(p.innerText);
        });

        // Extract table headers
        source.querySelectorAll('thead tr th').forEach(th => {
          header.push(th.innerText);
        });

        // Extract table rows
        source.querySelectorAll('tbody tr').forEach(tr => {
          var row = [];
          tr.querySelectorAll('td').forEach(td => {
            row.push(td.innerText);
          });
          rows.push(row);
        });

        // Build top content with paragraphs
        for (var i = 0; i < paragraph.length; i++) {
          top += paragraph[i] + '\n\n'; // Add each paragraph with line breaks
        }

        // Set font and text color for top content
        doc.setFont('helvetica');
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0); // Black color

        // Add top content to the document
        doc.text(20, 20, top);

        // Add table to the document
        doc.autoTable({
          head: [header],
          body: rows,
          didDrawPage: function(data) {
            // Only modify style on the first page
            if (data.pageCount === 1) {
              var headerCells = data.table.head[0].cells;
              for (var i = 0; i < headerCells.length; i++) {
                headerCells[i].styles.fillColor = [255, 255, 255];
                headerCells[i].styles.textColor = [255, 255, 255];
              }
            }
          },
          margin: {
            top: 60
          } // Adjust margin to accommodate top content
        });

        // Save the PDF
        doc.save('sales report.pdf');
      }

      //PRINTING INVENTORY REPORT
      function demoFromHTML2() {
        // Ensure jsPDF and autoTable are correctly initialized
        var {
          jsPDF
        } = window.jspdf;
        var doc = new jsPDF('p', 'pt', 'letter');

        // Source is the table
        var source = document.getElementById('content2');

        // Variables for content extraction
        var paragraph = [];
        var rows = [];
        var header = [];
        var top = '';

        // Extract paragraphs
        source.querySelectorAll('p').forEach(p => {
          paragraph.push(p.innerText);
        });

        // Extract table headers
        source.querySelectorAll('thead tr th').forEach(th => {
          header.push(th.innerText);
        });

        // Extract table rows
        source.querySelectorAll('tbody tr').forEach(tr => {
          var row = [];
          tr.querySelectorAll('td').forEach(td => {
            row.push(td.innerText);
          });
          rows.push(row);
        });

        // Build top content with paragraphs
        for (var i = 0; i < paragraph.length; i++) {
          top += paragraph[i] + '\n\n'; // Add each paragraph with line breaks
        }

        // Set font and text color for top content
        doc.setFont('helvetica');
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0); // Black color

        // Add top content to the document
        doc.text(20, 20, top);

        // Add table to the document
        doc.autoTable({
          head: [header],
          body: rows,
          didDrawPage: function(data) {
            // Only modify style on the first page
            if (data.pageCount === 1) {
              var headerCells = data.table.head[0].cells;
              for (var i = 0; i < headerCells.length; i++) {
                headerCells[i].styles.fillColor = [255, 255, 255];
                headerCells[i].styles.textColor = [255, 255, 255];
              }
            }
          },
          margin: {
            top: 60
          } // Adjust margin to accommodate top content
        });

        // Save the PDF
        doc.save('inventory_report.pdf');
      }

      //PRINTING FEEDBACK REPORT
      function demoFromHTML3() {
        // Ensure jsPDF and autoTable are correctly initialized
        var {
          jsPDF
        } = window.jspdf;
        var doc = new jsPDF('p', 'pt', 'letter');

        // Source is the table
        var source = document.getElementById('content3');

        // Variables for content extraction
        var paragraph = [];
        var rows = [];
        var header = [];
        var top = '';

        // Extract paragraphs
        source.querySelectorAll('p').forEach(p => {
          paragraph.push(p.innerText);
        });

        // Extract table headers
        source.querySelectorAll('thead tr th').forEach(th => {
          header.push(th.innerText);
        });

        // Extract table rows
        source.querySelectorAll('tbody tr').forEach(tr => {
          var row = [];
          tr.querySelectorAll('td').forEach(td => {
            row.push(td.innerText);
          });
          rows.push(row);
        });

        // Build top content with paragraphs
        for (var i = 0; i < paragraph.length; i++) {
          top += paragraph[i] + '\n\n'; // Add each paragraph with line breaks
        }

        // Set font and text color for top content
        doc.setFont('helvetica');
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0); // Black color

        // Add top content to the document
        doc.text(20, 20, top);

        // Add table to the document
        doc.autoTable({
          head: [header],
          body: rows,
          didDrawPage: function(data) {
            // Only modify style on the first page
            if (data.pageCount === 1) {
              var headerCells = data.table.head[0].cells;
              for (var i = 0; i < headerCells.length; i++) {
                headerCells[i].styles.fillColor = [255, 255, 255];
                headerCells[i].styles.textColor = [255, 255, 255];
              }
            }
          },
          margin: {
            top: 60
          } // Adjust margin to accommodate top content
        });

        // Save the PDF
        doc.save('feedback report.pdf');
      }


      //PRINTING USER LOGS REPORT
      function demoFromHTML4() {
        // Ensure jsPDF and autoTable are correctly initialized
        var {
          jsPDF
        } = window.jspdf;
        var doc = new jsPDF('p', 'pt', 'letter');

        // Source is the table
        var source = document.getElementById('content4');

        // Variables for content extraction
        var paragraph = [];
        var rows = [];
        var header = [];
        var top = '';

        // Extract paragraphs
        source.querySelectorAll('p').forEach(p => {
          paragraph.push(p.innerText);
        });

        // Extract table headers
        source.querySelectorAll('thead tr th').forEach(th => {
          header.push(th.innerText);
        });

        // Extract table rows
        source.querySelectorAll('tbody tr').forEach(tr => {
          var row = [];
          tr.querySelectorAll('td').forEach(td => {
            row.push(td.innerText);
          });
          rows.push(row);
        });

        // Build top content with paragraphs
        for (var i = 0; i < paragraph.length; i++) {
          top += paragraph[i] + '\n\n'; // Add each paragraph with line breaks
        }

        // Set font and text color for top content
        doc.setFont('helvetica');
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0); // Black color

        // Add top content to the document
        doc.text(20, 20, top);

        // Add table to the document
        doc.autoTable({
          head: [header],
          body: rows,
          didDrawPage: function(data) {
            // Only modify style on the first page
            if (data.pageCount === 1) {
              var headerCells = data.table.head[0].cells;
              for (var i = 0; i < headerCells.length; i++) {
                headerCells[i].styles.fillColor = [255, 255, 255];
                headerCells[i].styles.textColor = [255, 255, 255];
              }
            }
          },
          margin: {
            top: 60
          } // Adjust margin to accommodate top content
        });

        // Save the PDF
        doc.save('userlogs report.pdf');
      }
    </script>

</body>

</html>